name: Build  # Name of the workflow

on:  # Events that trigger this workflow
  push:  # Trigger when a commit is pushed to the repository
  pull_request:  # Trigger when a pull request is opened or updated

jobs:  # Define the jobs that will be executed

  test:  # Job name is 'test'
    runs-on: ${{ matrix.os }}  # Use matrix value to set the OS dynamically

    strategy:  # Define a matrix strategy for running multiple configurations
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]  # Specify OS to run on
        java: [8, 17, 21]  # Specify JVM versions to test with
        jvm_flags: [

          #Deja fait par le prof :
          # Xmx1024m taille max du heap 
          #Xss640k : Stack d<un thread
          # Xpkginfo:always : genere un fichier de package d<information
          "-XX:+UseCompressedOops -XX:+PrintFlagsFinal", #Memory control
          "-XX:+HeapDumpOnOutOfMemoryError -XX:+PrintFlagsFinal",  #Error management
          "-XX:+UseG1GC -XX:+PrintGCDetails -XX:+PrintGCDateStamps -Xloggc:gc.log -XX:+PrintFlagsFinal", #garbage colelction
          "-Dhttp.keepAlive=true -Dsun.net.http.errorstream.enableBuffering=true -XX:+PrintFlagsFinal", #Flags for HTTP requests / connections  optimization 
          "-XX:+AggressiveOpts -XX:+PrintFlagsFinal" #Threads Management and optimisation


        ]  # Matrix of JVM flags to test
      fail-fast: false  # Don't stop the workflow if one job fails




    name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}  # Dynamic job name for easier identification in UI

    steps:  # Steps within the job



      - name: Checkout  # Step to check out the code from the repository
        uses: actions/checkout@v4  # Checkout action to pull the latest code


        
      - name: Set up JDK ${{ matrix.java }}  # Set up the JDK for the current job based on matrix
        uses: actions/setup-java@v4  # Action to install Java
        with:
          java-version: ${{ matrix.java }}  # Use the specific JDK version from matrix
          distribution: 'zulu'  # Use the Zulu OpenJDK distribution
          cache: 'maven'  # Cache Maven dependencies to improve build times


#NEW ADDITION :
      - name: Apply JVM Flags  # Apply and log the JVM flags for clarity
        env:
            MAVEN_OPTS: ${{ matrix.jvm_flags }}  # Apply the specific JVM flags as environment variables
        run: |
            echo "Applying JVM flags: ${{ matrix.jvm_flags }}"  
            echo "Flaggy flaging all the flaggy flags"
          # Log the flags used for this run


      - name: Maven Compile  # Step to compile the project using Maven
        run: mvn -X compile -B --file pom.xml  # Run Maven with debug output in batch mode

      - name: Maven Verify  # Step to verify the project (typically running tests)
        run: mvn -X verify -B --file pom.xml  # Run Maven with debug output in batch mode


#NEW ADDITION :
      - name: Generate Coverage Report  # Generate the test coverage report
        run: mvn jacoco:report

    
      - name: Get JaCoCo Coverage
        id: coverage  
        run: |
              coverage=$(python3 config/coverage.py target/site/jacoco/jacoco.csv) 
              echo "COVERAGE=$coverage" >> $GITHUB_ENV
    
              
      - name: Upload Coverage Report  # Upload the coverage report as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: target/site/jacoco
